# This is a basic workflow to help you get started with Actions
name: Test the project

# Controls when the workflow will run
# More info: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      # Cloning the project on the server is the first step
      # More info: https://github.com/actions/checkout
      # 'run' for Running the command and 'uses' for Executing the action
      - name: Get the code
        uses: actions/checkout@v3

      # Installing dependencies i.e. Node.js but its already installed by deafult
      # More info: https://github.com/actions/setup-node
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        # This will install all dependencies in package-lock.json
        run: npm ci

      - name: Run the tests
        run: npm test
